version: "2"
services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
    links:
      - consul:consul
      - frontend:frontend
    depends_on:
      - consul
      - frontend
    restart: always
    command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"
  consul:
    image: progrium/consul:latest
    container_name: consul
    command: -server -bootstrap -ui-dir /ui
    hostname: "node1"
    restart: always
    mem_limit: 128m
    ports:
      - "8500:8500"
    dns:
      - 127.0.0.1
  influx:
    image: tutum/influxdb
    restart: always
    hostname: "node1"
    ports:
      - "8086:8086"
      - "8083:8083"
  serializer:
    build: serializer
    env_file: ./env.conf
    restart: always
    links:
      - influx:influx
    expose:
      - "8000"
    depends_on:
      - influx
  broker:
    build: broker
    env_file: ./env.conf
    restart: always
    links:
      - consul:consul
    expose:
      - "8000"
    depends_on:
      - serializer
      - sensor
      - consul
  sensor:
    build: sensor
    env_file: ./env.conf
    restart: always
    links:
      - consul:consul
    expose:
      - "8000"
    depends_on:
      - consul
  actuator:
    build: actuator
    env_file: ./env.conf
    restart: always
    links:
      - consul:consul
    expose:
      - "8000"
    depends_on:
      - broker
      - consul
  frontend:
    build: frontend
    env_file: ./env.conf
    restart: always
    links:
      - consul:consul
    ports:
      - "8000"
    depends_on:
      - serializer
      - actuator
      - consul
