version: "2"
services:
  nginx:
    build: nginx
    ports:
      - 80
    links:
      - consul:consul
    depends_on:
      - consul
    restart: always
    command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"
  consul:
      image: progrium/consul:latest
      command: -server -bootstrap -ui-dir /ui
      restart: always
      mem_limit: 128m
      ports:
        - 8500
      dns:
        - 127.0.0.1
  influx:
    image: tutum/influxdb
    container_name: influx
    volumes:
      - "./data:/data"
    ports:
      - 8086:8086
      - 8083:8083
  serializer:
    build: serializer
    env_file: ./env.conf
    links:
      - influx:influx
    ports:
      - "8000"
    depends_on:
      - influx
  broker:
    build: broker
    env_file: ./env.conf
    links:
      - serializer:serializer
    ports:
      - "1883"
    depends_on:
      - serializer
  sensor:
    build: sensor
    env_file: ./env.conf
    links:
      - broker:broker
    ports:
      - "8000"
    depends_on:
      - broker
  actuator:
    build: actuator
    env_file: ./env.conf
    links:
      - broker:broker
    ports:
      - "8000"
    depends_on:
      - broker
  frontend:
    build: frontend
    env_file: ./env.conf
    links:
      - serializer:serializer
      - actuator:actuator
    ports:
      - "8000"
    depends_on:
      - serializer
      - actuator
